-- setup_snowflake.sql
-- Corre esto UNA VEZ en Snowsight (o via SnowSQL) antes de usar el proyecto
-- de dbt de la Clase 7. Ajusta TU_USUARIO_SNOWFLAKE al final.

CREATE WAREHOUSE IF NOT EXISTS WH_TIENDANOVA
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS TIENDANOVA_DB;

CREATE SCHEMA IF NOT EXISTS TIENDANOVA_DB.RAW;
CREATE SCHEMA IF NOT EXISTS TIENDANOVA_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS TIENDANOVA_DB.MARTS;

CREATE ROLE IF NOT EXISTS ROLE_TIENDANOVA;
GRANT USAGE ON WAREHOUSE WH_TIENDANOVA TO ROLE ROLE_TIENDANOVA;
GRANT ALL ON DATABASE TIENDANOVA_DB TO ROLE ROLE_TIENDANOVA;
GRANT ALL ON ALL SCHEMAS IN DATABASE TIENDANOVA_DB TO ROLE ROLE_TIENDANOVA;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE TIENDANOVA_DB TO ROLE ROLE_TIENDANOVA;
GRANT ALL ON ALL TABLES IN SCHEMA TIENDANOVA_DB.RAW TO ROLE ROLE_TIENDANOVA;
GRANT ALL ON FUTURE TABLES IN SCHEMA TIENDANOVA_DB.RAW TO ROLE ROLE_TIENDANOVA;

-- Reemplaza por tu usuario real de Snowflake antes de correr esta linea:
GRANT ROLE ROLE_TIENDANOVA TO USER TU_USUARIO_SNOWFLAKE;

-- Tabla cruda de ejemplo para poder probar stg_ventas.sql de inmediato.
CREATE TABLE IF NOT EXISTS TIENDANOVA_DB.RAW.VENTAS (
    id_venta        STRING,
    id_sucursal     STRING,
    fecha_venta     DATE,
    monto_bruto     FLOAT,
    monto_descuento FLOAT
);

INSERT INTO TIENDANOVA_DB.RAW.VENTAS VALUES
    ('V-1001', 'lima',      '2026-09-01', 1200.00, 50.00),
    ('V-1002', 'arequipa',  '2026-09-01',  800.00,  0.00),
    ('V-1003', 'lima',      '2026-09-02',  950.00, 20.00),
    ('V-1004', 'trujillo',  '2026-09-02',  400.00, 10.00),
    ('V-1005', 'cusco',     '2026-09-02', 1500.00,  0.00);
